spring:
  security:
    user:
      name: user
      password: password
  application:
    name: website
  datasource:
    url: jdbc:postgresql://localhost:5433/website_db
    username: postgres
    password: postgres
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    hibernate:
      ddl-auto: update
    show-sql: true



server:
  port: 8080
